name: smartjuice_wear
description: SmartJuice Wear OS App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
